#配置端口号
server:
  port: 8001

spring:
  application:
    #配置名称
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.136.101:3306/payment8001?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc123

mybatis-plus:
  configuration:
    #显示SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置所有Entity别名类所在包的别名
  type-aliases-package: com.cloudpayment8001.pojo